name: phylogenies-bfms
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.9
  - r-base=4.4.1
  - biopython
  - tqdm
  - r-ape=5.8
  - r-ggplot2=3.5.1
  - r-gridextra
  - bioconductor-biostrings=2.74.0
  - r-pracma
  - r-httr=1.4.7
  - r-jsonlite=1.8.9
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-scales=1.3.0
  - r-pbapply
  - mmseqs2
  - wget
  - pip
